spring.application.name=platon-microservice-payments

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/SgestionLibreria_db?currentSchema=sgestionlibreria_payment
spring.datasource.username=SgestionLibreria
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=sgestionlibreria_payment
spring.jpa.open-in-view=false